admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
consults: c:\users\mpastor\soft\permanens\consults
homepage: homepage@domain.org
provider: My Organization
root_repository: c:\users\mpastor\soft\permanens
