admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
consults: x:\soft\permanens\consults
homepage: homepage@domain.org
models: x:\soft\permanens\models
provider: My Organization
root_repository: x:\soft\permanens
