name: permanens_app
channels:
  - default
  - conda-forge 
dependencies:
  - python=3.10
  - pip
  - setuptools
  - requests
  - flask
  - flask_cors
  - pyyaml
  - pytest
  - psycopg2
  - python-docx
  - XlsxWriter
  - appdirs
  - pip:
    - numpy
    - scikit-learn
    - statsmodels
     